edx/api-manager

README.md
swagger/api.yaml
swagger/oauth.yaml

Note that you can "validate" the Swagger spec by trying to generate an SDK with:
> `swagger-codegen generate -l swagger -i <https://raw version of api.yaml>`
That command requires the `swagger-codegen` tool (https://github.com/swagger-api/swagger-codegen).
@clintonb could you give this a once-over before I merge to master?

Updated README and added a first-draft Swagger spec.

---

swagger/api.yaml
swagger/heartbeat.yaml
swagger/oauth.yaml

also do a tiny amount of cleanup, like lowercasing schema definition names and adding an "id" stage variable for the heartbeat's response.

add heartbeat endpoint

---

swagger/heartbeat.yaml
swagger/oauth.yaml

@jcdyer I added some detail to the oauth swagger doc to better describe what each field means and added some examples. I ripped a lot of it off RFC6749 directly - can you quickly scan this for accuracy before I merge? Not urgent! I also added some detail around my custom heartbeat endpoint while I was in the codebase.

add more detail to local swagger documentation

---

swagger/heartbeat.yaml
swagger/oauth.yaml

because - while it's valid Swagger 2.0 and just a comment field - AWS can't handle its presence. ladies and gentlemen, I present 'the cloud'

commenting out examples

---

swagger/api.yaml
swagger/oauth.yaml

This parameter will enable clients to request alternative token types (e.g. JWT).
ECOM-4221

Added token_type parameter to OAuth access token request endpoint

---

swagger/api.yaml

"Discovery" is ambiguous to the point of being meaningless. "Catalog" is well-understood and better represents the purpose of the API/IDA

Renamed discovery endpoints

---

.travis.yml
Makefile
README.md
requirements/test.txt
scripts/aws/tests/fixtures/swagger.json
scripts/aws/tests/test_bootstrap.py
scripts/aws/tests/test_deploy.py
scripts/aws/tests/test_flip.py

@jzoldak updated pull request for your review. Files of interest: everything in `scripts/aws/tests` and the top-level `Makefile`. The only active test is in `test_deploy.py` because `moto` turns out to have virtually none of the high-level / newer boto calls I need, so I'm not entirely sure how much testing we can/want to do there right now.

add test stubs for flip.py and bootstrap.py

---

scripts/aws/tests/test_deploy.py

@jzoldak one more for you to review, please - filled out the stage-rotation logic tests to include two more assertions focused on negative cases:
- what happens when "rotating" from a stage that isn't in the rotation? (should: start from the beginning of the rotation order)
- what happens when there is no rotation? (should: throw an error)

add a few negative tests to stage rotation logic

---

Makefile

@jzoldak: please review. swagger-codegen 2.2.2 came out last week, I wanted to bump the version that we use for testing accordingly (the 2.2.1 release was from Aug 2016).
@mattdrayer @saleem-latif: fyi. Shouldn't impact your work, but you may wish to rebase.

Update swagger-codegen version used for testing to 2.2.2

---

swagger/api.yaml

@efagin @douglashall @saleem-latif -- had to fix the enterprise API endpoint mappings (see https://github.com/edx/edx-enterprise/pull/99).
This PR updates the hash used in the Github reference so it pulls in the updated mapping.

Update enterprise endpoint hash

---

Makefile
requirements/base.txt
requirements/test-requirements.txt

@jzoldak looks like moto just released 1.0.0, which has a bug (https://github.com/spulec/moto/issues/950) that can be worked around by also pulling in mock-2.0.0 directly, so I've done that here. Once moto bumps to 1.0.1+ we can probably safely remove mock from directly being required by this project.

bump dependencies

---

swagger/api.yaml

@efagin here is the corresponding PR for the Enterprise API updates for the missing query parameter mappings.

Update Enterprise API references to latest hash

---

scripts/aws/README.md
scripts/aws/deploy.py
swagger/api.yaml

Hi @efagin , @mattdrayer , @douglashall 
Please take a look at the PR, I have added a new stage variable named `gateway_host` that will contain the api manager's host.

ENT-472: Add gateway_host stage variable for api deployments

---

swagger/api.yaml

Hi @efagin , @douglashall ,
Please take a look at this, I have updated "ref" URLs for enterprise api config. Enterprise API config now points to [0.38.5](https://github.com/edx/edx-enterprise/releases/tag/0.38.5) that contains the changes merged in https://github.com/edx/edx-enterprise/pull/146
FYI, @zubair-arbi , @asadiqbal08

ENT-472: Update api.yaml refs for enterprise api.

---

swagger/api.yaml

- routes for login/logout endpoints
- updated definitions to properly map path parameters
see: https://github.com/edx/registrar/compare/zhancock/api-manager
this will require a followup PR to point the registrar commit hash back to master once validated

registrar api update

---

swagger/api.yaml
tests/test_all.yaml
tests/test_catalog.yaml
tests/test_discovery.yaml

Separate the `course-discovery` endpoints into a base `discovery` and `catalog` endpoint structure, since in an ideal world `catalog` would likely be its own separate IDA

Separate discovery/catalog endpoint structure

---

swagger/api.yaml

Follow up to the registrar API v2 release - need to add a proxy section for it in the API manager.

Add registrar v2 API proxy

---

swagger/api.yaml

@edx/masters-devs 
Follow up on https://github.com/edx/registrar/pull/189, need to remove registrar v1 mock api from our Amazon proxy.
ticket number: EDUCATOR-4676

Remove Registrar V1 Mock API from Amazon API proxy

---

swagger/api.yaml

Update refs to get a trailing slash on detail route. I don't think this will fix the 400, but just checking

Update refs to enterprise catalog IDA

---

swagger/api.yaml
tests/test_enterprise.yaml

This change uses the same implementation of the existing v1 enterprise
endpoints and merely adds a v2 shim that points to the same place. This
gives more consistent endpoints which will hopefully make it easier for
customers to migrate their code.
ENT-2938

Add all missing enterprise v1 endpoints to v2

---

Makefile

GoCD agents no longer expose java to the code that runs
on them. In order to unblock api-manager builds, we are
specifically adding a make target that allows us to
refer the GoCD java.
https://openedx.atlassian.net/browse/ARCHBOM-1807

feat: Add GoCD-specific make target.

---

swagger/api.yaml
tests/test_enterprise.yaml

**Description:** Add api gateway spec for version v3 of `learner-summary` endpoint so that LPR V1 API can be accessed through new learner-summary endpoint.
**JIRA:** https://openedx.atlassian.net/browse/ENT-4881
**Dependency:** https://github.com/edx/edx-enterprise-data/pull/264

feat: add v3 endpoint for enterprise learner summary endpoint

---

.github/workflows/upgrade-python-requirements.yml

Reverts edx/api-manager#142
This PR was made as a follow up to the cleanup job for reusable workflow. Now as we are going to revert that [PR](https://github.com/edx/api-manager/pull/139) too so firstly we have to revert this edx/api-manager#142 PR.

Revert "fix: use branch name directly"

---

.github/workflows/upgrade-python-requirements.yml

Reverts edx/api-manager#139
This repo needs some dependencies(related to pycurl) specific to the repo to be installed first before running tests and the reusable workflow that we have at edx/.github does not have this step in it. This is the reason make upgrade is failing on this repo. After discussion with the team, We decided to drop the usage of reusable workflow in this repo and revert to the old upgrade workflow that was being used in this repo.

Revert "refactor: Updated 'upgrade requirements' workflow to use reusable workflows"

---

scripts/aws/deploy.py
scripts/aws/deploy_studio.py

fix: import common deploy package with absolute path
another follow-on attempt to fix the gocd pipeline error that does not occur locally.

fix: import common deploy package with absolute path

---

scripts/__init__.py
scripts/aws/deploy.py
scripts/aws/deploy_studio.py

fix: make scripts directory a package, for absolute imports.
Make the top level `scripts` director a package, to fix ModuleNotFoundError?

fix: make scripts directory a package, for absolute imports.

---

scripts/aws/monitor.py

fix: use enum value for nodejs18, not explicit version

fix: use enum value for nodejs18, not explicit version

---

swagger/api.yaml

file_assets was inadvertently left as a v1 in the last merge

feat: TNL-10746 fix integrations to all be v0 versions

---

scripts/aws/deploy.py
swagger/api.yaml
tests/test_enterprise.yaml

This PR adds a definition for license-manager assign endpoint on the Omnibus API to expose it to Gateway. 
Host variable is also added to pick up host value for the service. https://github.com/edx/edx-internal/pull/9905
**JIRA**: https://2u-internal.atlassian.net/browse/ENT-7995

feat: Define license assign endpoint on Gateway

---

scripts/aws/common/deploy.py

Reverts edx/api-manager#257
GoCD `stage-edx-api` failed on the modified line of code with the following error: ```
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the PutRestApi operation: Errors found during import:
Unable to create model for 'body_1': Model name must be alphanumeric: body_1
```

Revert "Bszabo/tnl 11327 file upload"

---

swagger/api.yaml

This PR is an attempt to fix the error that came up during deploying api to Gateway. 
```
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the PutRestApi operation: Errors found during import:
Unable to create model for 'body_1': Model name must be alphanumeric: body_1

fix: rename body param for assign endpoint

---

swagger/api.yaml

This change will include 201 in gateway responses for correct service to gateway response mapping.

fix: include missing response for bulk-enroll

---

swagger/api.yaml

Description:
Update hash for the fix of adding trailing slash and 301 response code to the subscription list endpoint

[ENT-8345] fix: add trailing slash & 301 response to subscription endpoint
