edx/api-manager

swagger/oauth.yaml
@jcdyer can you take a look and let me know if this can be merged? These changes are in response to your feedback in PR #1.
=> add optional refresh_token to oauth2 response

README.md
@clintonb significant update to README. mind reviewing before I merge to master? this is for https://openedx.atlassian.net/browse/ARCH-40.
=> update README with capabilities list

scripts/aws/monitor.py
update IAM role to enable api gateway to push logs to  cloudwatch and minor improvements
=> adding part to enable api gateway to push logs to cloudwatch

scripts/aws/monitor.py, scripts/aws/templates/index.js.j2
=> lambda function needs to be with vpc config

requirements/base.txt
Make VersionEye happy, and by proxy, make myself happy.
=> Update boto* dependency versions

README.md, requirements/base.txt, requirements/test.txt
=> bump versioneye project ID and a handful of dependency versions

.gitignore, scripts/aws/README.md, scripts/aws/deploy.py, swagger/api.yaml, tests/test_all.yaml, tests/test_enterprise.yaml
Hi @mattdrayer , @efagin ,
Please take a look at the PR and share your thoughts.
__JIRA ticket:__ [ENT-238](https://openedx.atlassian.net/browse/ENT-238)
=> ENT-238: add 'Enterprise' namespace to edX API gateway

requirements/base.txt, requirements/test.txt, scripts/aws/deploy.py, scripts/aws/monitor.py
isolate just these dependency bumps, to see where travis is breaking...
=> bump a few dependencies

swagger/api.yaml
@efagin -- updating to the latest rev of the enterprise endpoint configuration -- hopefully this does the trick.
=> Update enterprise endpoint hashes to cc960ff version

requirements/base.txt, requirements/test-requirements.txt, scripts/aws/README.md
@saleem-latif I updated the README to remove those old references to environment variables. Could you please review this PR?
=> remove unused env variables from README, and bump a few dependencies

swagger/api.yaml
=> Updating hash for Enterprise endpoints.

swagger/api.yaml, tests/test_enterprise.yaml
This adds new Enterprise Catalog API endpoints for retrieving catalog data
associated with the authenticated user's EnterpriseCustomer.
ENT-341
=> Add Enterprise Catalog API endpoints.

swagger/api.yaml, tests/test_enterprise.yaml
=> ENT-341 Updating Enterprise API endpoints.

swagger/api.yaml
fix POST requests incorrectly mapping to GET
=> Fix GET/POST issue

swagger/api.yaml
Should not produce any functional changes.  This just references a commit in the master branch now
=> update hash to registrar master

README.md, swagger/api.yaml, tests/test_all.yaml, tests/test_discovery.yaml
Also renames catalog ida references to discovery
=> Add ref to courses endpoint in discovery

swagger/api.yaml, tests/test_discovery.yaml
Link to https://github.com/edx/course-discovery/pull/1967 and add basic tests for new endpoints
=> Add ref to new discovery yaml

swagger/api.yaml
https://openedx.atlassian.net/browse/EDUCATOR-4442
=> Remove registrar IDA explicit endpoints and use proxy instead.

Makefile, scripts/aws/deploy.py, swagger/api.yaml, tests/test_enterprise.yaml
Adds in the catalog list and detail endpoints to v2 of the
enterprise API in API gateway.
ENT-2578
=> Add enterprise-catalog IDA to enterprise APIs

scripts/aws/monitor.py
Attempt to fix pipeline failure for out of date node version
=> Switch node version to LTS

.github/workflows/ci.yml, requirements/base.txt, requirements/pip.txt, requirements/pip_tools.txt, requirements/test.txt, scripts/aws/bootstrap.py, scripts/aws/deploy.py, scripts/aws/monitor.py
**Issue:** [BOM-2545](https://openedx.atlassian.net/browse/BOM-2545)
- Removed support for `Python 3.5`.
- Fixed quality failures.
=> BOM-2545: Remove support for Python35

Makefile, requirements/base.txt, requirements/pip.txt, requirements/test.txt
Also install the pip requirements for upgrades.
=> fix: Upgrade python requirements.

.github/workflows/upgrade-python-requirements.yml
JIRA: https://openedx.atlassian.net/browse/BOM-2502
=> fix: Fixed the Upgrade Requirements job failure

Makefile, requirements/base.txt, requirements/pip.txt, requirements/pip_tools.txt, requirements/test.in, requirements/test.txt
There was a typing mistake in requirements file name. Fixed it.
=> fix: Corrected the requirements file name

scripts/aws/monitor.py
fix: user newer nodejs version in monitor.py
more fixing of the gocd pipeline
=> fix: user newer nodejs version in monitor.py

scripts/aws/common/deploy.py
Reverts edx/api-manager#260 -- didn't properly pick up latest code from before
=> Revert "Bszabo/tnl 11327 file upload"

.github/workflows/ci.yml
- Added `Python 3.11` support in GitHub CI.
=> feat: add python311 support

docs/decisions/0001-API-strategy-and-change-management-process.rst
Proposing an ADR to form up an API change management process to better communicate upstream API changes internally to enterprise dev teams and externally to enterprise customers.
=> docs: ADR for API change management process

swagger/api.yaml
Description:
Updated commit for the api.yaml file for license assign end point
the commit for reference [ef94bee](https://github.com/openedx/license-manager/commit/ef94beec59be750234ebadf9c97e91c362ffa6b9)
JIRA:
https://2u-internal.atlassian.net/jira/software/c/projects/ENT/issues/ENT-9502
=> Updated commit for the api.yaml file for license assign end point

requirements/base.txt, requirements/constraints.txt, requirements/pip.txt, requirements/pip_tools.txt, requirements/test.txt, scripts/aws/tests/test_bootstrap.py, scripts/aws/tests/test_deploy_common.py, scripts/aws/tests/test_flip.py
**Description:**
Remove moto<5.0 constraint and update dependencies
**Issue Link**
https://github.com/edx/api-manager/issues/276
=> Remove moto<5.0 constraint and update dependencies
